version: '3.5'

networks:
    LAN:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.210.0.0/24

services:
    zookeeper:
        image: confluentinc/cp-zookeeper:latest
        container_name: C1_zookeeper
        environment: 
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
        ports:
            - "22181:2181"

    broker:
        image: confluentinc/cp-enterprise-kafka:latest
        container_name: C1_kafka
        depends_on:
            - zookeeper
        ports: 
            - "29092:29092"
            - "9092:9092"
        environment: 
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
            KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
            KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
            CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: broker:29092
            CONFLUENT_METRICS_REPORTER_ZOOKEEPER_CONNECT: zookeeper:2181
            CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
            CONFLUENT_METRICS_ENABLE: 'true'
            CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'

        networks:
            default:
            LAN:
                ipv4_address: 172.210.0.20

    schema-registry:
        image: confluentinc/cp-schema-registry
        container_name: C1_schema_registry
        depends_on:
            - zookeeper
            - broker
        ports:
            - "8081:8081"
        environment:
            SCHEMA_REGISTRY_HOST_NAME: schema-registry
            SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: 'zookeeper:2181'

    control-center:
        image: confluentinc/cp-enterprise-control-center:latest
        container_name: C1_control_center
        depends_on:
            - zookeeper
            - broker
            - schema-registry
        ports:
            - 9021:9021
        environment: 
            CONTROL_CENTER_BOOTSTRAP_SERVERS: 'broker:29092'
            CONTROL_CENTER_ZOOKEEPER_CONNECT: 'zookeeper:2181'
            # CONTROL_CENTER_CONNECT_MONGOCONNECT_CLUSTER: 'mongoconnect:8083'
            # CONTROL_CENTER_KSQL_URL: "http://ksql-server:8088"
            # CONTROL_CENTER_KSQL_ADVERTISED_URL: "http://localhost:8088"
            CONTROL_CENTER_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
            CONTROL_CENTER_REPLICATION_FACTOR: 1
            CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
            CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
            CONFLUENT_METRICS_TOPIC_REPLICATION: 1
            PORT: 9021

    rest-proxy:
        image: confluentinc/cp-kafka-rest:latest
        container_name: C1_kafka_rest_proxy
        depends_on:
            - zookeeper
            - broker
        ports:
            - 8082:8082
        environment:
            KAFKA_REST_HOST_NAME: rest-proxy
            KAFKA_REST_BOOTSTRAP_SERVERS: 'broker:29092'
            KAFKA_REST_LISTENERS: "http://0.0.0.0:8082"
            KAFKA_REST_SCHEMA_REGISTRY_URL: 'http://schema-registry:8081'

    kafka-topics-ui:
        image: landoop/kafka-topics-ui:0.9.4
        container_name: C1_kafka_ui
        depends_on:
            - zookeeper
            - broker
            - rest-proxy
        ports:
            - 28000:8000
        environment:
            KAFKA_REST_PROXY_URL: "http://rest-proxy:8082/"
            PROXY: "true"